commit_21996 ------------------------------------------------------------------------ r21996 | vboxsync | 2009-08-05 21:07:00 +0800 (Wed, 05 Aug 2009) | 1 line
icmp_error: don't crash when msrc is NULL (debug builds only).
------------------------------------------------------------------------