commit_49862 ------------------------------------------------------------------------ r49862 | vboxsync | 2013-12-10 12:53:09 +0800 (Tue, 10 Dec 2013) | 2 lines
pxping_pmgr_icmp6_error: g/c unused variable.

------------------------------------------------------------------------