commit_77270 ------------------------------------------------------------------------ r77270 | vboxsync | 2019-02-12 15:25:10 +0800 (Tue, 12 Feb 2019) | 11 lines
Runtime: Fix compilation with LibreSSL <2.7.0.
BIO_up_ref() was provided since LibreSSL-2.7.0.
When 2.6.x is used we get an error:

src/VBox/Runtime/common/crypto/ssl-openssl.cpp:275:17: error: ‘BIO_up_ref’ was not declared in this scope
                 BIO_up_ref(pSession->pBio); /* our reference. */
                 ^~~~~~~~~~

See also: https://bugs.gentoo.org/673800
The patch is submitted under MIT license.
Thank you Stefan Strogin for the patch.
------------------------------------------------------------------------