commit_56700 ------------------------------------------------------------------------ r56700 | vboxsync | 2015-06-30 21:25:36 +0800 (Tue, 30 Jun 2015) | 1 line
RTGetOptPrintError: Don't crash on VERR_GETOP_TINVALID_ARGUMENT_FORMAT if pDef is NULL.
------------------------------------------------------------------------