commit_74935 ------------------------------------------------------------------------ r74935 | vboxsync | 2018-10-19 13:22:30 +0800 (Fri, 19 Oct 2018) | 1 line
Attempt to correct dyld: Symbol not found __ZN7nsDebug9AssertionEPKcS1_S1_i in VBoxXPCOM.dylib, similar to changes in r125944
------------------------------------------------------------------------