commit_42008 ------------------------------------------------------------------------ r42008 | vboxsync | 2012-07-04 03:13:43 +0800 (Wed, 04 Jul 2012) | 4 lines
libs/libvpx: reverting the 78887 change due to build failure on linux 64 and solaris
error: yasm: FATAL: 'dwarf2' is not a valid debug format for object format 'bin'

------------------------------------------------------------------------